package com.zyp.mango.mybatis.dao;

import com.zyp.mango.mybatis.model.SysConfig;
import java.util.List;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Wed Feb 07 16:11:04 CST 2024
     */
    int insert(SysConfig row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Wed Feb 07 16:11:04 CST 2024
     */
    List<SysConfig> selectAll();
}